# Generated by Django 4.2 on 2024-01-20 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'معلومات الموقع',
                'verbose_name_plural': 'معلومات الموقع',
            },
        ),
    ]
