# Generated by Django 4.2 on 2024-01-20 10:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_info_public_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='payment_methods',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
