# Generated by Django 4.2 on 2024-01-20 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_info_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='terms',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
