# Generated by Django 4.2 on 2024-01-31 23:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_info_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='terms_conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
