# Generated by Django 4.2 on 2024-01-31 23:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_info_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='return_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
