# Generated by Django 4.2 on 2024-01-31 23:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_info_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
