# Generated by Django 4.2 on 2024-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_info_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='primary_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم اتصال أساسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='secondary_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم اتصال ثانوي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الواتساب'),
            preserve_default=False,
        ),
    ]
