# Generated by Django 4.2 on 2024-01-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_info_email_info_primary_number_info_secondary_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='info',
            name='primary_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اتصال أساسي'),
        ),
        migrations.AlterField(
            model_name='info',
            name='secondary_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اتصال ثانوي'),
        ),
        migrations.AlterField(
            model_name='info',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب'),
        ),
    ]
