# Generated by Django 5.0.1 on 2024-01-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.bank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='الاسم بالكامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='iban',
            field=models.CharField(default='', max_length=255, verbose_name='ايبان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='', max_length=255, verbose_name='رقم الهوية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='swift_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SWIFT CODE'),
        ),
    ]
