# Generated by Django 5.0.1 on 2024-01-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_bank_name_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.bank', verbose_name='اسم البنك'),
        ),
    ]
