# Generated by Django 5.0.1 on 2024-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ايبان'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الهوية'),
        ),
    ]
