# Generated by Django 5.0.1 on 2024-01-17 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('approved', 'مقبول'), ('disapproved', 'غير مقبول'), ('done', 'مكتمل')], max_length=50, verbose_name='حالة الطلب')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('total', models.FloatField(verbose_name='الإجمالي')),
                ('products', models.ManyToManyField(to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
    ]
