# Generated by Django 5.0.1 on 2024-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='', max_length=255, verbose_name='رقم الطلب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('approved', 'مقبول'), ('disapproved', 'غير مقبول'), ('done', 'مكتمل')], max_length=50, null=True, verbose_name='حالة الطلب'),
        ),
    ]
