# Generated by Django 4.2 on 2024-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=255, verbose_name='رقم الطلب في المتجر'),
        ),
    ]
