# Generated by Django 4.2 on 2024-01-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'المنتجات المطلوبة'},
        ),
    ]
