# Generated by Django 4.2 on 2024-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_with_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='الإجمالي مع ضريبة العمولة'),
        ),
    ]
