# Generated by Django 4.2 on 2024-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_total_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_value',
            field=models.FloatField(blank=True, null=True, verbose_name='قيمة العمولة'),
        ),
    ]
