# Generated by Django 4.2 on 2024-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_commission_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_tax_value',
            field=models.FloatField(blank=True, null=True, verbose_name='قيمة ضريبة العمولة'),
        ),
    ]
