# Generated by Django 4.2 on 2024-02-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
    ]
